### ISSUE TITLE
Program does not remember chosen directories on restart

### ISSUE THREAD

**Issue by crecs** [supremesonicbrazil/SLSK#10]
I think it would be a great improvement to have SLSK remember the path to your Steam games folder and to where you chose your backup folder to be. The setting could be saved as soon as it is set, and the config could be set in `$XDG_CONFIG_HOME/SLSK` or `$HOME/.config/SLSK` if the former doesn't exist.

I'm not a developer in this kind of work, but I got the information about XDG from [here](https://standards.freedesktop.org/basedir-spec/latest/ar01s03.html). Doing the above would be the XDG way to do it I think.

**Comment by supremesonicbrazil** [comment]
Ah yes, I'm familiar with XDG, good idea :)

Thanks for pointing out, I'm already fixing some things I found after finding a replacement MOBO for my PC. Had to install Ubuntu here, and I just found out Steam is installed to a different directory depending on how you install it, *and* the `userdata` folder may not always use STEAMID64 (the one that starts with 7656*, I noticed my Steam install actually uses a shorter STEAMID3), so as soon as I'm done fixing those I'll add this as well.

**Comment by supremesonicbrazil** [comment]
Hey I've pushed it to the `dev` branch so you can give it a go :)

**Comment by crecs** [comment]
That feature is working!

**Comment by supremesonicbrazil** [comment]
Alright, gonna merge it right away :)
