### ISSUE TITLE
Remove things that do not require root out of INSTALL.sh

### ISSUE THREAD

**Issue by lnmds** [supremesonicbrazil/SLSK#2]
Title is pretty self-explanatory.

Compiling should be as simple as `./configure && make`

Installing should be as simple as `sudo make install`

`INSTALL.sh` does both, and it requires root permissions since the start

**Comment by supremesonicbrazil** [comment]
Fixed it, there's now two scripts, BUILD.sh and INSTALL.sh. Only the latter requires root permissions, so compiling is secure now.
