### ISSUE TITLE
Segmentation fault when calculating approx. size

### ISSUE THREAD

**Issue by Cybolic** [supremesonicbrazil/SLSK#21]
When calculating the approximate size of saving the save game data for "Destination Sol", SLSK crashes with a segfault. This happens both when trying the package compiled by malkavi and when trying with a installation compiled from source on Fedora 27.

I think the issue might be that it doesn't find any save files (the DB.csv lists "$STEAMAPPS/*.ini", which doesn't yield any results on my system) since I haven't played the game yet.

**Comment by supremesonicbrazil** [comment]
Hey there, I guess I fixed it. When scanning saves/configs, games appearing in the list even though no saves/configs exist may happen, as with Destination Sol. The path ends in a bunch of `*.ini` files, so the program goes back one level to its parent directory - the Steam game folder - and counts all files with that extension, putting them all in an `entryInfoList`. It was empty though, and the program tried to access the first entry, which was null, so it segfaulted there.

I've put an extra layer of protection before that, so the program actually checks if the `entryInfoList` is not empty. It's still odd not checking for the files' existence so the game isn't even added to the list, but still, this fixes the segfault. I've pushed it to the `dev` branch along with #22 , so if you wanna test 'em both, make yourself at home :)
