### ISSUE TITLE
`make` is not listed as a dependency

### ISSUE THREAD

**Issue by crecs** [supremesonicbrazil/SLSK#8]
I tried to compile SLSK and it did not generate the executable in /opt/SLSK without `make` installed. After reading BUILD.sh, I saw that it was using "make" on line 18.

I understand very little about the build process for C programs, but I think line 18 means that either `make` is a dependency absent from the readme list of dependencies, or somehow qmake was supposed to be used but it wasn't.

After installing `make` everything went fine, so I believe adding `make` to the dependency list in the readme would be a good decision for aiding others who wish to install.

**Comment by lnmds** [comment]
I would say to have the `build-essentials` package or its variant on your linux distro installed(`base-devel` on Arch Linux, for example), it is kind of implicit to have it installed if you have your machine for development purposes.

Usually those packages already provide a basic set to compile C programs, including `make` and `gcc`.

**Comment by supremesonicbrazil** [comment]
Sorry about that guys, I'll put `make` alongside `g++` in README in a sec.
